kind: Template
apiVersion: v1
metadata:
  labels:
    app: service-test
  name: service-test
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: service-test
    name: service-test
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: service-test
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: service-test
    name: server-pod
  spec:
    containers:
    - name: service-test
      image: centos:centos7
      ports:
      - containerPort: 8080
        name: test-port
        protocol: TCP
      command: ["/bin/bash"]
      args: ["-c", "python -m SimpleHTTPServer 8080 & disown; while true ; do curl -sSI http://service-test:8080 ; sleep 1 ; done"]